create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dut_top_inst/ctrl_inst/state[0]} {dut_top_inst/ctrl_inst/state[1]} {dut_top_inst/ctrl_inst/state[2]} {dut_top_inst/ctrl_inst/state[3]} {dut_top_inst/ctrl_inst/state[4]} {dut_top_inst/ctrl_inst/state[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/adder_en[0]} {dut_top_inst/dtp_inst/systolic_module/adder_en[1]} {dut_top_inst/dtp_inst/systolic_module/adder_en[2]} {dut_top_inst/dtp_inst/systolic_module/adder_en[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_00[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_00[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_00[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_00[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_00[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_00[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_00[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_00[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_01[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_01[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_01[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_01[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_01[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_01[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_01[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_01[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_11[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_11[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_11[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_11[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_11[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_11[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_11[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_11[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_02[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_02[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_02[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_02[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_02[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_02[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_02[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_02[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_32[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_32[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_32[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_32[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_32[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_32[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_32[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_32[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 24 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_22[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_22[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_10[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_10[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_10[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_10[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_10[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_10[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_10[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_10[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_21[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_21[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_21[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_21[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_21[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_21[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_21[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_21[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 24 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_01[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_01[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_33[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_33[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_33[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_33[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_33[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_33[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_33[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_33[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 8 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_13[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_13[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_13[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_13[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_13[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_13[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_13[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_13[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 8 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/w_in[2][0]} {dut_top_inst/dtp_inst/systolic_module/w_in[2][1]} {dut_top_inst/dtp_inst/systolic_module/w_in[2][2]} {dut_top_inst/dtp_inst/systolic_module/w_in[2][3]} {dut_top_inst/dtp_inst/systolic_module/w_in[2][4]} {dut_top_inst/dtp_inst/systolic_module/w_in[2][5]} {dut_top_inst/dtp_inst/systolic_module/w_in[2][6]} {dut_top_inst/dtp_inst/systolic_module/w_in[2][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 24 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_03[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_03[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 8 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_31[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_31[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_31[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_31[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_31[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_31[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_31[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_31[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 24 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_10[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_10[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 8 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_22[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_22[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_22[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_22[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_22[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_22[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_22[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_22[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 8 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_23[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_23[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_23[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_23[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_23[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_23[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_23[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_23[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 24 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_21[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_21[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 4 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/pe_en[0]} {dut_top_inst/dtp_inst/systolic_module/pe_en[1]} {dut_top_inst/dtp_inst/systolic_module/pe_en[2]} {dut_top_inst/dtp_inst/systolic_module/pe_en[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 24 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_23[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_23[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 8 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/w_in[0][0]} {dut_top_inst/dtp_inst/systolic_module/w_in[0][1]} {dut_top_inst/dtp_inst/systolic_module/w_in[0][2]} {dut_top_inst/dtp_inst/systolic_module/w_in[0][3]} {dut_top_inst/dtp_inst/systolic_module/w_in[0][4]} {dut_top_inst/dtp_inst/systolic_module/w_in[0][5]} {dut_top_inst/dtp_inst/systolic_module/w_in[0][6]} {dut_top_inst/dtp_inst/systolic_module/w_in[0][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 8 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_12[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_12[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_12[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_12[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_12[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_12[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_12[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_12[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 8 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_20[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_20[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_20[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_20[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_20[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_20[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_20[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_20[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 24 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_02[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_02[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 24 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_31[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_31[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 24 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_12[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_12[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 8 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_30[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_30[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_30[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_30[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_30[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_30[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_30[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_30[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 24 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_00[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_00[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 24 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_32[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_32[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 4 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/mul_en[0]} {dut_top_inst/dtp_inst/systolic_module/mul_en[1]} {dut_top_inst/dtp_inst/systolic_module/mul_en[2]} {dut_top_inst/dtp_inst/systolic_module/mul_en[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 24 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_11[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_11[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 24 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_13[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_13[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 24 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_30[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_30[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 8 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/w_in[3][0]} {dut_top_inst/dtp_inst/systolic_module/w_in[3][1]} {dut_top_inst/dtp_inst/systolic_module/w_in[3][2]} {dut_top_inst/dtp_inst/systolic_module/w_in[3][3]} {dut_top_inst/dtp_inst/systolic_module/w_in[3][4]} {dut_top_inst/dtp_inst/systolic_module/w_in[3][5]} {dut_top_inst/dtp_inst/systolic_module/w_in[3][6]} {dut_top_inst/dtp_inst/systolic_module/w_in[3][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 24 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_20[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_20[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 24 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/p_out_33[0]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[1]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[2]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[3]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[4]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[5]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[6]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[7]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[8]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[9]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[10]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[11]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[12]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[13]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[14]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[15]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[16]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[17]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[18]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[19]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[20]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[21]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[22]} {dut_top_inst/dtp_inst/systolic_module/p_out_33[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 8 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/i_out_03[0]} {dut_top_inst/dtp_inst/systolic_module/i_out_03[1]} {dut_top_inst/dtp_inst/systolic_module/i_out_03[2]} {dut_top_inst/dtp_inst/systolic_module/i_out_03[3]} {dut_top_inst/dtp_inst/systolic_module/i_out_03[4]} {dut_top_inst/dtp_inst/systolic_module/i_out_03[5]} {dut_top_inst/dtp_inst/systolic_module/i_out_03[6]} {dut_top_inst/dtp_inst/systolic_module/i_out_03[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 8 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list {dut_top_inst/dtp_inst/systolic_module/w_in[1][0]} {dut_top_inst/dtp_inst/systolic_module/w_in[1][1]} {dut_top_inst/dtp_inst/systolic_module/w_in[1][2]} {dut_top_inst/dtp_inst/systolic_module/w_in[1][3]} {dut_top_inst/dtp_inst/systolic_module/w_in[1][4]} {dut_top_inst/dtp_inst/systolic_module/w_in[1][5]} {dut_top_inst/dtp_inst/systolic_module/w_in[1][6]} {dut_top_inst/dtp_inst/systolic_module/w_in[1][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 10 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list {dut_top_inst/add_out[0]} {dut_top_inst/add_out[1]} {dut_top_inst/add_out[2]} {dut_top_inst/add_out[3]} {dut_top_inst/add_out[4]} {dut_top_inst/add_out[5]} {dut_top_inst/add_out[6]} {dut_top_inst/add_out[7]} {dut_top_inst/add_out[8]} {dut_top_inst/add_out[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 24 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list {dut_top_inst/din_mem_out[0]} {dut_top_inst/din_mem_out[1]} {dut_top_inst/din_mem_out[2]} {dut_top_inst/din_mem_out[3]} {dut_top_inst/din_mem_out[4]} {dut_top_inst/din_mem_out[5]} {dut_top_inst/din_mem_out[6]} {dut_top_inst/din_mem_out[7]} {dut_top_inst/din_mem_out[8]} {dut_top_inst/din_mem_out[9]} {dut_top_inst/din_mem_out[10]} {dut_top_inst/din_mem_out[11]} {dut_top_inst/din_mem_out[12]} {dut_top_inst/din_mem_out[13]} {dut_top_inst/din_mem_out[14]} {dut_top_inst/din_mem_out[15]} {dut_top_inst/din_mem_out[16]} {dut_top_inst/din_mem_out[17]} {dut_top_inst/din_mem_out[18]} {dut_top_inst/din_mem_out[19]} {dut_top_inst/din_mem_out[20]} {dut_top_inst/din_mem_out[21]} {dut_top_inst/din_mem_out[22]} {dut_top_inst/din_mem_out[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 24 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list {dut_top_inst/dout_mem[0]} {dut_top_inst/dout_mem[1]} {dut_top_inst/dout_mem[2]} {dut_top_inst/dout_mem[3]} {dut_top_inst/dout_mem[4]} {dut_top_inst/dout_mem[5]} {dut_top_inst/dout_mem[6]} {dut_top_inst/dout_mem[7]} {dut_top_inst/dout_mem[8]} {dut_top_inst/dout_mem[9]} {dut_top_inst/dout_mem[10]} {dut_top_inst/dout_mem[11]} {dut_top_inst/dout_mem[12]} {dut_top_inst/dout_mem[13]} {dut_top_inst/dout_mem[14]} {dut_top_inst/dout_mem[15]} {dut_top_inst/dout_mem[16]} {dut_top_inst/dout_mem[17]} {dut_top_inst/dout_mem[18]} {dut_top_inst/dout_mem[19]} {dut_top_inst/dout_mem[20]} {dut_top_inst/dout_mem[21]} {dut_top_inst/dout_mem[22]} {dut_top_inst/dout_mem[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list dut_top_inst/done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list dut_top_inst/start]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list dut_top_inst/w_out]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list dut_top_inst/dtp_inst/systolic_module/wshift]]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
